name = ""
main = "dist/index.mjs"
compatibility_date = "2022-06-05"
kv_namespaces = [
	{ binding = "BOT_KV", id = "<ID>", preview_id = "<ID>" }
]

[triggers]
crons = ["0 0 * * *"]

[build]
command = "npm run build"

# The necessary secrets are:
# - token
# - discord_public_key
# Run `wrangler secret put <NAME> <VALUE>` for each of these
